### ISSUE TITLE
git aws.push not wirking

### ISSUE THREAD

**Issue by markotron** [ayush/eb-deploy#2]
Hello, first of all I would like to thank you for the script :)
I've been using it for few months and everything worked fine until yesterday.  

I think that the problem is in the git aws.push line. I'm getting this output: 

Writing objects: 100% (131/131), 68.89 MiB | 10.01 MiB/s, done.
Total 131 (delta 2), reused 0 (delta 0)
remote: processing ...............................................

This processing thing lasts forever...

Do you have an idea what could be the problem? 

Tnx.

**Comment by ayush** [comment]
This is working fine for me. Perhaps your s3 bucket got full? Let me know if this is still an issue.
