### ISSUE TITLE
Question: Where does `eb` tool come from

### ISSUE THREAD

**Issue by alexbeletsky** [ayush/eb-deploy#3]
Thanks a lot for [article](http://blog.glugbot.com/automate-deployment/) and tool.

As far as I can see from script, it assumes that `eb` is already installed in CI machine? How come? How it's being installed there?

**Comment by ayush** [comment]
@alexbeletsky it is explicitly [downloaded](https://github.com/ayush/eb-deploy/blob/master/eb-deploy#L164), [expanded](https://github.com/ayush/eb-deploy/blob/master/eb-deploy#L166) and [added to PATH](https://github.com/ayush/eb-deploy/blob/master/eb-deploy#L177).

**Comment by alexbeletsky** [comment]
Got it, thanks!
